name: Update Documentation

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  SCHEME: "AccessibilityDocumentation"
  XCODE_VERSION: '~>15'
  DERIVED_DATA_PATH: './DerivedData/'
  DESTINATION: 'generic/platform=iOS'
  HOSTING_BASE_PATH: 'AccessibilityDocumentation'
  OUTPUT_URL: 'https://vodgroup.github.io/AccessibilityDocumentation/documentation/accessibilitydocumentation/'

jobs:
  update-docs:
    runs-on: 'macos-13'
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: latest
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Build
        run: |
          xcodebuild docbuild -scheme AccessibilityDocumentation -destination 'generic/platform=iOS' -derivedDataPath ${{ env.DERIVED_DATA_PATH }}
          
      - name: Build
        run: |
          $(xcrun --find docc) process-archive transform-for-static-hosting ${{ env.DERIVED_DATA_PATH }}Build/Products/Debug-iphoneos/AccessibilityDocumentation.doccarchive --output-path ../docs --hosting-base-path AccessibilityDocumentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ../docs

  deploy:
    needs: update-docs
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: 'macos-13'
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${ env.ARTEFACT_PATH }documentation/${{ env.SCHEME_LOWERCASED }}/
    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      
